<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>clc_loc</name>
   <tag></tag>
   <elementGuidId>d4a6aba9-0aa4-49d7-9762-cb07b8366e60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;block-global-header-menu&quot;]/div/ul/li[4]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;block-global-header-menu&quot;]/div/ul/li[4]/a</value>
   </webElementProperties>
</WebElementEntity>
