<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click1</name>
   <tag></tag>
   <elementGuidId>b9edb8f6-2ae9-43ea-b69e-487f0f5485bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;block-content&quot;]/div/header/div[2]/div/form/div[2]/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;block-content&quot;]/div/header/div[2]/div/form/div[2]/button</value>
   </webElementProperties>
</WebElementEntity>
